---
  AWSTemplateFormatVersion: '2010-09-09'
  Description: 'Amazon EKS - Node Group'
  Parameters:
    KeyName:
      Description: The EC2 Key Pair to allow SSH access to the instances
      Type: AWS::EC2::KeyPair::KeyName
    VpcId:
      Description: The VPC of the worker instances
      Type: AWS::EC2::VPC::Id
    Subnets:
      Description: The subnets where workers can be created.
      Type: List<AWS::EC2::Subnet::Id>
    NodeImageId:
      Type: AWS::EC2::Image::Id
      Default: ami-73a6e20b
      Description: AMI id for the node instances. 
  Resources: 
    EKSInstanceLaunchTemplate:
      Type: "AWS::EC2::LaunchTemplate"
      Properties:
        LaunchTemplateName: EKSWorkerNodes
        LaunchTemplateData: 
          SecurityGroups: 
            - String
          UserData:
            Fn::Base64: !Sub |
              #!/bin/bash -xe
              CA_CERTIFICATE_DIRECTORY=/etc/kubernetes/pki
              CA_CERTIFICATE_FILE_PATH=$CA_CERTIFICATE_DIRECTORY/ca.crt
              MODEL_DIRECTORY_PATH=~/.aws/eks
              MODEL_FILE_PATH=$MODEL_DIRECTORY_PATH/eks-2017-11-01.normal.json
              mkdir -p $CA_CERTIFICATE_DIRECTORY
              mkdir -p $MODEL_DIRECTORY_PATH
              curl -o $MODEL_FILE_PATH https://s3-us-west-2.amazonaws.com/amazon-eks/1.10.3/2018-06-05/eks-2017-11-01.normal.json
              aws configure add-model --service-model file://$MODEL_FILE_PATH --service-name eks
              aws eks describe-cluster --region=us-west-2 --name=catsndogsECScluster --query 'cluster.{certificateAuthorityData: certificateAuthority.data, endpoint: endpoint}' > /tmp/describe_cluster_result.json
              cat /tmp/describe_cluster_result.json | grep certificateAuthorityData | awk '{print $2}' | sed 's/[,\"]//g' | base64 -d >  $CA_CERTIFICATE_FILE_PATH
              MASTER_ENDPOINT=$(cat /tmp/describe_cluster_result.json | grep endpoint | awk '{print $2}' | sed 's/[,\"]//g')
              INTERNAL_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
              sed -i s,MASTER_ENDPOINT,$MASTER_ENDPOINT,g /var/lib/kubelet/kubeconfig
              sed -i s,CLUSTER_NAME,catsndogsECScluster,g /var/lib/kubelet/kubeconfig
              sed -i s,REGION,us-west-2,g /etc/systemd/system/kubelet.service
              sed -i s,MASTER_ENDPOINT,$MASTER_ENDPOINT,g /etc/systemd/system/kubelet.service
              sed -i s,INTERNAL_IP,$INTERNAL_IP,g /etc/systemd/system/kubelet.service
              DNS_CLUSTER_IP=10.100.0.10
              if [[ $INTERNAL_IP == 10.* ]] ; then DNS_CLUSTER_IP=172.20.0.10; fi
              sed -i s,DNS_CLUSTER_IP,$DNS_CLUSTER_IP,g  /etc/systemd/system/kubelet.service
              sed -i s,CERTIFICATE_AUTHORITY_FILE,$CA_CERTIFICATE_FILE_PATH,g /var/lib/kubelet/kubeconfig
              sed -i s,CLIENT_CA_FILE,$CA_CERTIFICATE_FILE_PATH,g  /etc/systemd/system/kubelet.service
              systemctl daemon-reload
              systemctl restart kubelet
          IamInstanceProfile: 
            Arn: arn:aws:iam::710487389845:instance-profile/eks-nodes-stack-group-NodeInstanceProfile-D2645KNRG0DLx
          KeyName: !Ref KeyName